name: Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '*'
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - master
      - 'test/*'

env:
  CI: "true"
  FORCE_COLOR: "true"

jobs:
  test:
    name: node v${{ matrix.node }}, pptr ${{ matrix.puppeteer_version }}, ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node:
          - 15
          # - 14
          # - 12
        puppeteer_version:
          - 8.0.0 # Chromium 90.0.4427.0, Feb 18, 2021

        os:
          - ubuntu-latest
    #           - macOS-latest
    # - windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: 'Fix for: error fsevents@2.1.2: The platform "linux" is incompatible with this module.'
        run: npx json -I -f package.json -e 'this.resolutions={}'

      - name: yarn install
        uses: bahmutov/npm-install@v1

      - name: yarn bootstrap
        run: yarn bootstrap

      - name: install puppeteer ${{ matrix.puppeteer_version }}
        run: yarn lerna add --dev puppeteer@${{ matrix.puppeteer_version }}

      - name: lerna link
        run: yarn lerna link

      - name: lerna build
        run: yarn lerna run build --concurrency 1

      - name: debug
        run: |
          yarn list --pattern "puppeteer|puppeteer-extra"
          file node_modules/puppeteer-extra/dist/index.cjs.js
      - uses: microsoft/playwright-github-action@v1

      - name: test
        uses: GabrielBB/xvfb-action@v1
        env:
          DISPLAY: ":99.0"
        with:
          run: yarn test-ci
